services:
  - type: web
    name: gdz-bot-simple
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: BOT_TOKEN
        value: 8456034289:AAFocvpSevSlavQh_FJnbyJ-WdpVa4Zw9Hw
      - key: WEB_APP_URL
        value: https://razetka2010.github.io/gdz-navigator/
      - key: PORT
        value: 3000
    healthCheckPath: /health
    autoDeploy: true
